In [ ]:
import numpy as np

In [ ]:
def logic_gate(w1, w2, b):
    sigmoid = lambda x : 1/(1+np.exp(-x))
    return lambda x1, x2: sigmoid(w1 * x1 + w2 * x2 + b)

In [ ]:
def test(gate):
    for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
        print("{} , {} : {}".format(a, b, np.round(gate(a,b))))

In [ ]:
or_gate = logic_gate(20, 20, -10)
test(or_gate)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


In [ ]:
or_gate_01 = logic_gate(1,1,-0.5)
test(or_gate_01)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


# Part-II: Implement the operations of AND, NOR and NAND gates

### AND GATE

In [ ]:
and_gate = logic_gate(1,1,-1.5)
print("AND GATE \n")
test(and_gate)


AND GATE 

0 , 0 : 0.0
0 , 1 : 0.0
1 , 0 : 0.0
1 , 1 : 1.0


### NAND GATE

In [ ]:
nand_gate = logic_gate(-0.5,-0.5,0.7)
print("NAND GATE \n")
test(nand_gate)

NAND GATE 

0 , 0 : 1.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 0.0


### NOR GATE

In [ ]:
nor_gate = logic_gate(-1,-1,0.5)
print("NOR GATE \n")
test(nor_gate)

NOR GATE 

0 , 0 : 1.0
0 , 1 : 0.0
1 , 0 : 0.0
1 , 1 : 0.0



# Part-III: Limitations of single neuron for XOR operation

In [ ]:
xor = logic_gate(1,1,-0.5)
test(xor)

0 , 0 : 0.0
0 , 1 : 1.0
1 , 0 : 1.0
1 , 1 : 1.0


# XOR Gate

In [ ]:
def xor(x1,x2):
    or_val = int(x1 or x2)
    and_val = int(not(x1 and x2))
    xor_val = int(or_val and and_val)
    return xor_val

In [ ]:
test(xor)

0 , 0 : 0
0 , 1 : 1
1 , 0 : 1
1 , 1 : 0


# Part-IV: Logic Gates using Keras library

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Function to create and run the model
def run_logic_gate_model(gate_name, x_train, y_train):
    # Create the model
    model = Sequential()
    model.add(Dense(16, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])

    # Train the model
    model.fit(x_train, y_train, epochs=100, verbose=0)

    # Predict the output values
    predictions = model.predict(x_train)
    predictions = np.round(predictions)

    # Print the predictions
    print(f"{gate_name} Gate Predictions:")
    print(predictions.flatten().astype(int))
    print()


In [ ]:

# Input and output values for the logic gates
input_values = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# AND gate
and_output = np.array([0, 0, 0, 1])
run_logic_gate_model("AND", input_values, and_output)

# OR gate
or_output = np.array([0, 1, 1, 1])
run_logic_gate_model("OR", input_values, or_output)

# NOT gate
not_output = np.array([1, 0, 1, 0])
run_logic_gate_model("NOT", input_values, not_output)

# NAND gate
nand_output = np.array([1, 1, 1, 0])
run_logic_gate_model("NAND", input_values, nand_output)

# NOR gate
nor_output = np.array([1, 0, 0, 0])
run_logic_gate_model("NOR", input_values, nor_output)

# XOR gate
xor_output = np.array([0, 1, 1, 0])
run_logic_gate_model("XOR", input_values, xor_output)


1/1 [==============================] - 0s 79ms/step
AND Gate Predictions:
[0 0 0 1]

1/1 [==============================] - 0s 60ms/step
OR Gate Predictions:
[1 1 1 1]

1/1 [==============================] - 0s 63ms/step
NOT Gate Predictions:
[1 0 0 0]

1/1 [==============================] - 0s 52ms/step
NAND Gate Predictions:
[1 1 1 0]



1/1 [==============================] - 0s 54ms/step
NOR Gate Predictions:
[0 0 0 0]



1/1 [==============================] - 0s 85ms/step
XOR Gate Predictions:
[1 0 1 0]

